// <auto-generated />
namespace BabaRh.AccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataBase_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataBase_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091521409_DataBase_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
