// <auto-generated />
namespace BabaRh.AccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WCF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WCF));
        
        string IMigrationMetadata.Id
        {
            get { return "202105180708142_WCF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
